source "https://rubygems.org"

gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
gem 'dotenv', groups: [:development, :test]
eval_gemfile(plugins_path) if File.exist?(plugins_path)
