# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for  Android App Distribution" 
  lane :dev do
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:938618055262:android:afa784367fd48e02b162cf",
      firebase_cli_token: "1//03CNS3LjzWnwpCgYIARAAGAMSNwF-L9Irk-OFsCNt7P6jF1_KqLoaFfRmeIK04znq2ibbZGPGJgfhfgG9hWYYjXkxv2bQwn8BAhs",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "mohamedmaher.personal@gmail.com",
      release_notes: "test release notes",
    )
  end
  lane :stage do
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:938618055262:android:afa784367fd48e02b162cf",
      firebase_cli_token: "1//03CNS3LjzWnwpCgYIARAAGAMSNwF-L9Irk-OFsCNt7P6jF1_KqLoaFfRmeIK04znq2ibbZGPGJgfhfgG9hWYYjXkxv2bQwn8BAhs",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      groups: "app_testers",
      release_notes: "test release notes",
    )
  end
end